name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Type Check
        run: bun run typecheck

      - name: Lint Check
        run: bun run typecheck

      - name: Run Tests with Coverage
        run: bun run test

      - name: Debug Environment
        run: uname -a

      - name: Verify Package Contents
        run: |
          test -f dist/index.mjs || (echo "Missing index.mjs" && exit 1)
          test -f dist/index.cjs || (echo "Missing index.cjs" && exit 1)
          test -f dist/styles.css || (echo "Missing styles.css" && exit 1)
          test -f dist/baseline-kit.css || (echo "Missing baseline-kit.css" && exit 1)
          test -d dist/theme || (echo "Missing theme directory" && exit 1)
